openapi: 3.0.0

info:
  title: Mock Accounts API
  description: A mock up of a simple account management API for sample purposes.
  version: "1.0.0"
  contact:
    name: Ashley Kinard
    email: ashleymkinard@gmail.com
    url: https://ashleykinard.pro/

security:
  - userApiKey: []

servers:
  - url: https://example.com

tags:
  - name: Accounts
    description: Endpoints that manage accounts.
  - name: Account Licenses
    description: Endpoints that manage account licenses.
  - name: Product Licenses
    description: Endpoints that manage product licenses.

paths:
  /account:
    $ref: paths/accounts.yml#/account
  /account/{accountId}:
    $ref: paths/accounts.yml#/account_{accountId}
  /account/{accountId}/licenses:
    $ref: paths/accounts.yml#/account_{accountId}_licenses
  /account/{accountId}/licenses/{licenseId}:
    $ref: paths/accounts.yml#/account_{accountId}_licenses_{licenseId}

components:
  securitySchemes:
    userApiKey:
      type: apiKey
      in: header
      name: api-key
