openapi: 3.0.0

info:
  title: "Mock Accounts API"
  description: A mock up of an account management API.
  version: "1.0.0"
  contact:
    name: Ashley Kinard
    email: ashleymkinard@gmail.com
    url: https://ashleykinard.pro/

security:
  - userApiKey: []

servers:
  - url: https://example.com

tags:
  - name: Accounts
  - name: Product Licenses

paths:
  /license/{accountId}/{licenseId}:
    $ref: paths/licenses.yml#/license_{accountId}_{licenseId}

components:
  securitySchemes:
    userApiKey:
      type: apiKey
      in: header
      name: api-key